[build]
command = "npm run build"
publish="/build'
base = "/"

# netlify.toml

[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301

[[redirects]]
  from = "/about"
  to = "/about-us"
  status = 302

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"

